{application,online,
             [{description,"online"},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib,ssl,session]},
              {mod,{online_app,[]}},
              {env,[]},
              {modules,[guardant,license4,license_agent,online_app,
                        online_pulse_replicator,online_sup]}]}.
