

-record(cluster_server, {
  name,
  port,
  id,
  key,
  proto = hls :: hls | m4s | m4f | rtmp | tshttp,
  channel_limit,
  uptime,
  is_source = false :: boolean(),
  is_peer = false :: boolean(),
  public,
  config2 = false,
  version,
  build,
  bandwidth_usage,
  cpu_usage,
  memory_usage,
  output_bitrate,
  input_bitrate,
  rtmp_port,
  rtsp_port,
  turn_port,
  https_port,
  meta,
  stream_count,
  total_streams,
  client_count,
  fetched_at,
  error,
  vsaas,
  vsaas_endpoint,
  rproxy,
  rproxy_streampoint_key,
  rproxy_endpoint_auth,
  camera_alarm,
  camera_alarm_listen,
  camera_alarm_catch,
  persistent = false,
  is_remote = true,
  fetch_timeout,
  stale_timeout,
  failed_ports :: #{Proto :: atom() => [non_neg_integer()]},
  hostname_unreachable = false :: false | true,
  large_time_difference :: true | false | undefined,
  utc
}).
