%%% This file was automatically generated by snmpc_mib_to_hrl version 5.4.1
%%% Date: 02-Dec-2019::17:05:58
-ifndef('FLUSSONIC-MIB').
-define('FLUSSONIC-MIB', true).

%% Oids

-define(flussonicModule, [1,3,6,1,4,1,36342]).

-define(flussonic, [1,3,6,1,4,1,36342,1]).

-define(streams, [1,3,6,1,4,1,36342,1,1]).
-define(streamsNum, [1,3,6,1,4,1,36342,1,1,1]).
-define(streamsNum_instance, [1,3,6,1,4,1,36342,1,1,1,0]).

-define(streamsTable, [1,3,6,1,4,1,36342,1,1,2]).

-define(streamsEntry, [1,3,6,1,4,1,36342,1,1,2,1]).
-define(sIndex, 1).
-define(sName, 2).
-define(sClientCount, 3).
-define(sRetryCount, 4).
-define(sLifeTime, 5).
-define(sBitrate, 6).
-define(sBytesIn, 7).
-define(sBytesOut, 8).
-define(sStatus, 9).

-define(accounting, [1,3,6,1,4,1,36342,1,2]).
-define(totalClients, [1,3,6,1,4,1,36342,1,2,1]).
-define(totalClients_instance, [1,3,6,1,4,1,36342,1,2,1,0]).

-define(serverStatus, [1,3,6,1,4,1,36342,1,3]).
-define(schedulerLoad, [1,3,6,1,4,1,36342,1,3,1]).
-define(schedulerLoad_instance, [1,3,6,1,4,1,36342,1,3,1,0]).

-define(flussonicConformance, [1,3,6,1,4,1,36342,2]).

-define(streamGroup, [1,3,6,1,4,1,36342,2,1]).

-define(statGroup, [1,3,6,1,4,1,36342,2,2]).

-define(statusGroup, [1,3,6,1,4,1,36342,2,3]).


%% Range values
-define(low_streamsNum, 0).
-define(high_streamsNum, 4294967295).
-define(low_sName, 0).
-define(high_sName, 255).
-define(low_sClientCount, 0).
-define(high_sClientCount, 4294967295).
-define(low_sRetryCount, 0).
-define(high_sRetryCount, 4294967295).
-define(low_totalClients, 0).
-define(high_totalClients, 4294967295).
-define(low_schedulerLoad, 0).
-define(high_schedulerLoad, 4294967295).


%% Enum definitions from sStatus
-define(sStatus_destroy, 6).
-define(sStatus_createAndWait, 5).
-define(sStatus_createAndGo, 4).
-define(sStatus_notReady, 3).
-define(sStatus_notInService, 2).
-define(sStatus_active, 1).

%% Default values
-define(default_streamsNum, 0).
-define(default_totalClients, 0).
-define(default_schedulerLoad, 0).

-endif.
